"""
FundMe — Curated Opportunity Catalogue.
This is the trusted, human-verified opportunity data layer.
AI ranks/filters these; it does NOT hallucinate new ones.
"""

CURATED_OPPORTUNITIES = [
    {
        "id": "startup-india-dpiit-recognition",
        "title": "DPIIT Startup India Recognition",
        "organization": "Department for Promotion of Industry and Internal Trade (DPIIT)",
        "description": "Official government recognition for startups enabling tax benefits, self-certification, faster patent examination, and access to government tenders. A foundational step for any Indian startup.",
        "category": "government",
        "tags": ["India", "government", "recognition", "tax-benefits", "all-sectors"],
        "eligibility_summary": "Incorporated as Private Ltd, LLP or Partnership. Entity age < 10 years. Annual turnover < ₹100 Cr. Working towards innovation/improvement of products or services.",
        "startup_stages": ["idea", "validation", "mvp", "pre-seed", "seed"],
        "geography": ["India"],
        "domain_focus": [],
        "founder_criteria": [],
        "funding_amount": "Non-monetary (benefits & recognition)",
        "benefits": ["Tax exemption under Sec 80IAC", "Self-certification compliance", "Fast-track patent filing", "Government tender eligibility", "Fund of Funds access"],
        "required_docs": ["Incorporation certificate", "Founder details", "Business description", "Innovation statement"],
        "official_link": "https://www.startupindia.gov.in/content/sih/en/startupgov/startup-recognition-page.html",
        "deadline": "Rolling",
        "source_name": "Startup India Portal",
    },
    {
        "id": "nidhi-prayas-dst",
        "title": "NIDHI PRAYAS — Proof of Concept Grant",
        "organization": "National Initiative for Developing and Harnessing Innovations (NIDHI), DST",
        "description": "Grants up to ₹10 lakhs for early-stage technology innovators to develop proof of concept and prototypes. Specifically targets pre-incorporation innovators and student entrepreneurs.",
        "category": "grant",
        "tags": ["India", "deeptech", "hardware", "prototype", "student", "pre-seed"],
        "eligibility_summary": "Individual innovators or teams (not necessarily incorporated). Technology-based innovation with prototype potential. Hosted at NIDHI-supported incubators.",
        "startup_stages": ["idea", "validation", "mvp"],
        "geography": ["India"],
        "domain_focus": ["deeptech", "hardware", "biotech", "cleantech"],
        "founder_criteria": ["student", "individual"],
        "funding_amount": "Up to ₹10 Lakhs",
        "benefits": ["₹10L grant", "Incubation support", "Mentorship", "IP guidance", "Lab access"],
        "required_docs": ["Innovation brief", "Prototype plan", "Team details", "Incubator letter"],
        "official_link": "https://nidhi.dst.gov.in/prayas",
        "deadline": "Rolling (batch-based)",
        "source_name": "DST NIDHI",
    },
    {
        "id": "birac-biotechnology-ignition-grant",
        "title": "BIRAC Biotechnology Ignition Grant (BIG)",
        "organization": "Biotechnology Industry Research Assistance Council (BIRAC)",
        "description": "Flagship grant of up to ₹50 lakhs for biotech and life sciences startups at the idea or early validation stage. One of India's most prestigious deep science startup grants.",
        "category": "grant",
        "tags": ["India", "biotech", "lifesciences", "healthtech", "agritech", "deep-tech"],
        "eligibility_summary": "Indian startups or individuals with a biotech innovation. Must apply through a BIRAC-empanelled Business Management Agency. Less than 5 years old.",
        "startup_stages": ["idea", "validation", "mvp"],
        "geography": ["India"],
        "domain_focus": ["biotech", "healthtech", "agritech", "medtech"],
        "founder_criteria": [],
        "funding_amount": "Up to ₹50 Lakhs",
        "benefits": ["₹50L non-dilutive grant", "Industry mentorship", "IP support", "Network access"],
        "required_docs": ["Project proposal", "Team CV", "Innovation description", "Budget plan", "Incorporation (if any)"],
        "official_link": "https://www.birac.nic.in/big.php",
        "deadline": "Annual (check portal)",
        "source_name": "BIRAC",
    },
    {
        "id": "meity-tide-20",
        "title": "MeitY TIDE 2.0 — Technology Incubation and Development",
        "organization": "Ministry of Electronics & IT (MeitY)",
        "description": "Support for ICT-based startups through a network of incubators across India. Provides seed funding, incubation, and mentorship to early-stage tech startups.",
        "category": "incubator",
        "tags": ["India", "ICT", "software", "AI", "fintech", "edtech", "govtech"],
        "eligibility_summary": "Technology startup (ICT domain). Incorporated entity preferred. Early-stage to growth stage. Must apply through a MeitY-TIDE empanelled incubator.",
        "startup_stages": ["validation", "mvp", "pre-seed"],
        "geography": ["India"],
        "domain_focus": ["AI", "fintech", "edtech", "SaaS", "IoT"],
        "founder_criteria": [],
        "funding_amount": "Up to ₹75 Lakhs",
        "benefits": ["Seed funding up to ₹75L", "Incubation space", "Mentorship", "Industry connects"],
        "required_docs": ["Pitch deck", "Business plan", "Team details", "Product demo"],
        "official_link": "https://tide20.meity.gov.in/",
        "deadline": "Rolling (cohort-based)",
        "source_name": "MeitY TIDE 2.0",
    },
    {
        "id": "aim-atal-innovation-mission",
        "title": "Atal Innovation Mission — Startup Programs",
        "organization": "NITI Aayog / Atal Innovation Mission",
        "description": "AIM supports early-stage startups across India through Atal Incubation Centres (AICs) and Atal Community Innovation Centres. Access mentorship, funding, and national visibility.",
        "category": "incubator",
        "tags": ["India", "innovation", "social-impact", "all-sectors", "student"],
        "eligibility_summary": "Indian startup or entrepreneur. Preference for social innovation and underserved markets. Hosted through AIM-supported incubators.",
        "startup_stages": ["idea", "validation", "mvp", "pre-seed"],
        "geography": ["India"],
        "domain_focus": [],
        "founder_criteria": ["student", "first-time-founder"],
        "funding_amount": "Varies by program",
        "benefits": ["Incubation", "Mentorship", "Grants", "Government recognition", "National network"],
        "required_docs": ["Application form", "Business idea summary", "Team profile"],
        "official_link": "https://aim.gov.in/",
        "deadline": "Rolling",
        "source_name": "Atal Innovation Mission",
    },
    {
        "id": "yc-startup-school",
        "title": "Y Combinator Startup School",
        "organization": "Y Combinator",
        "description": "Free online program by YC for early-stage founders. Weekly learning modules, community access, and optional Demo Day. A global launchpad used by tens of thousands of founders.",
        "category": "accelerator",
        "tags": ["Global", "pre-seed", "idea-stage", "community", "YC", "free"],
        "eligibility_summary": "Open to any founder globally, at any stage. No incorporation required. Completely free.",
        "startup_stages": ["idea", "validation", "mvp"],
        "geography": ["Global"],
        "domain_focus": [],
        "founder_criteria": ["first-time-founder", "student"],
        "funding_amount": "Free (no equity taken for Startup School)",
        "benefits": ["Weekly YC curriculum", "Founder community", "YC alumni network", "Optional Demo Day"],
        "required_docs": ["Basic application"],
        "official_link": "https://www.startupschool.org/",
        "deadline": "Rolling",
        "source_name": "Y Combinator",
    },
    {
        "id": "yc-batch-application",
        "title": "Y Combinator Batch Application (W/S)",
        "organization": "Y Combinator",
        "description": "The world's most competitive accelerator. $500K standard deal for 7% equity. Two batches per year. Among the highest-signal accelerators globally.",
        "category": "accelerator",
        "tags": ["Global", "accelerator", "top-tier", "seed", "equity"],
        "eligibility_summary": "Any startup globally. No minimum traction required but strong team and insight expected. Must have co-founders strongly recommended.",
        "startup_stages": ["mvp", "pre-seed", "seed"],
        "geography": ["Global"],
        "domain_focus": [],
        "founder_criteria": [],
        "funding_amount": "$500K for 7% equity",
        "benefits": ["$500K funding", "YC network", "Demo Day", "YC brand", "Alumni community"],
        "required_docs": ["Application form", "Pitch video", "Product demo link"],
        "official_link": "https://www.ycombinator.com/apply",
        "deadline": "Bi-annual (check portal)",
        "source_name": "Y Combinator",
    },
    {
        "id": "google-for-startups-accelerator-india",
        "title": "Google for Startups Accelerator India",
        "organization": "Google",
        "description": "3-month equity-free accelerator for Seed to Series A stage tech startups in India. Offers Google Cloud credits, mentorship from Googlers, and global network access.",
        "category": "accelerator",
        "tags": ["India", "AI", "ML", "SaaS", "deep-tech", "equity-free"],
        "eligibility_summary": "India-based tech startup. Seed to Series A stage. Focus on AI/ML companies preferred. Must have a working product.",
        "startup_stages": ["mvp", "pre-seed", "seed"],
        "geography": ["India"],
        "domain_focus": ["AI", "ML", "SaaS", "deeptech"],
        "founder_criteria": [],
        "funding_amount": "Equity-free + $200K Google Cloud credits",
        "benefits": ["$200K+ cloud credits", "Mentorship", "Google network", "Google brand validation"],
        "required_docs": ["Application form", "Pitch deck", "Product demo"],
        "official_link": "https://startup.google.com/programs/accelerator/india/",
        "deadline": "Annual (check portal)",
        "source_name": "Google for Startups",
    },
    {
        "id": "microsoft-founders-hub",
        "title": "Microsoft for Startups Founders Hub",
        "organization": "Microsoft",
        "description": "Free program providing Azure credits, GitHub, Microsoft 365, and startup tools to early-stage founders. No equity, no investment required. Apply online in minutes.",
        "category": "accelerator",
        "tags": ["Global", "cloud", "SaaS", "AI", "free", "equity-free", "tools"],
        "eligibility_summary": "Any startup globally. No incorporation required. Pre-seed to Series A. Must have a product concept.",
        "startup_stages": ["idea", "validation", "mvp", "pre-seed"],
        "geography": ["Global"],
        "domain_focus": [],
        "founder_criteria": [],
        "funding_amount": "Up to $150K Azure credits + tools",
        "benefits": ["Azure credits", "GitHub Enterprise", "Microsoft 365", "Technical support"],
        "required_docs": ["Online application", "Product description"],
        "official_link": "https://foundershub.startups.microsoft.com/",
        "deadline": "Rolling",
        "source_name": "Microsoft for Startups",
    },
    {
        "id": "aws-activate-startup",
        "title": "AWS Activate for Startups",
        "organization": "Amazon Web Services",
        "description": "AWS credits, technical support, and startup resources for early-stage companies. Up to $100K in credits to build on AWS infrastructure.",
        "category": "accelerator",
        "tags": ["Global", "cloud", "SaaS", "infrastructure", "equity-free"],
        "eligibility_summary": "Early-stage startup. Associated with an approved investor, incubator, or accelerator preferred. No incorporation required for Founders tier.",
        "startup_stages": ["idea", "validation", "mvp", "pre-seed"],
        "geography": ["Global"],
        "domain_focus": [],
        "founder_criteria": [],
        "funding_amount": "Up to $100K AWS credits",
        "benefits": ["AWS credits", "Technical support", "Training", "Startup community access"],
        "required_docs": ["Online application", "Startup description"],
        "official_link": "https://aws.amazon.com/activate/",
        "deadline": "Rolling",
        "source_name": "AWS",
    },
    {
        "id": "nasscom-10000-startups",
        "title": "NASSCOM 10000 Startups",
        "organization": "NASSCOM",
        "description": "India's largest tech startup program. Offers incubation, acceleration, mentorship, and market access for early-stage tech startups across India.",
        "category": "incubator",
        "tags": ["India", "tech", "SaaS", "AI", "deeptech", "B2B"],
        "eligibility_summary": "Indian tech startup. Early to growth stage. Product must have a technology core.",
        "startup_stages": ["validation", "mvp", "pre-seed", "seed"],
        "geography": ["India"],
        "domain_focus": ["AI", "SaaS", "fintech", "edtech", "healthtech"],
        "founder_criteria": [],
        "funding_amount": "Varies (connect to investors)",
        "benefits": ["Incubation", "Mentorship", "Investor connects", "NASSCOM network", "Visibility"],
        "required_docs": ["Application form", "Pitch deck", "Team profile"],
        "official_link": "https://10000startups.com/",
        "deadline": "Rolling",
        "source_name": "NASSCOM",
    },
    {
        "id": "iim-ahmedabad-ledge",
        "title": "IIMA LEDGE — Startup Fellowship",
        "organization": "IIM Ahmedabad CIIE.CO",
        "description": "Flagship fellowship for early-stage founders by one of India's top business schools. Provides structured mentorship, investor access, and cohort support.",
        "category": "fellowship",
        "tags": ["India", "fellowship", "pre-seed", "mentorship", "all-sectors"],
        "eligibility_summary": "Early-stage Indian founders. Preference for founders with validated concept or MVP. Applications open periodically.",
        "startup_stages": ["validation", "mvp", "pre-seed"],
        "geography": ["India"],
        "domain_focus": [],
        "founder_criteria": [],
        "funding_amount": "Program support (non-monetary primary)",
        "benefits": ["IIMA mentorship", "Investor intros", "Cohort community", "IIM brand"],
        "required_docs": ["Application form", "Startup overview", "Founder bio"],
        "official_link": "https://ciie.co/",
        "deadline": "Cohort-based",
        "source_name": "CIIE.CO IIMA",
    },
    {
        "id": "tiss-svayam-social-enterprise",
        "title": "SVAYAM Social Innovation Fellowship",
        "organization": "Tata Institute of Social Sciences",
        "description": "Fellowship for social entrepreneurs addressing grassroots problems in India. Especially relevant for founders working in education, health, livelihoods, and rural development.",
        "category": "fellowship",
        "tags": ["India", "social-impact", "fellowship", "NGO", "rural", "education"],
        "eligibility_summary": "Social entrepreneurs with an idea or early-stage social enterprise. Focus on impact in India.",
        "startup_stages": ["idea", "validation", "mvp"],
        "geography": ["India"],
        "domain_focus": ["edtech", "healthtech", "social-impact"],
        "founder_criteria": ["social-entrepreneur"],
        "funding_amount": "Fellowship stipend + support",
        "benefits": ["Fellowship grant", "TISS network", "Mentorship", "Research support"],
        "required_docs": ["Application essay", "Project proposal", "CV"],
        "official_link": "https://tiss.edu/",
        "deadline": "Annual",
        "source_name": "TISS",
    },
    {
        "id": "india-climate-collaborative-grant",
        "title": "India Climate Collaborative — Startup Grants",
        "organization": "India Climate Collaborative",
        "description": "Early-stage grants and support for climate-focused startups in India. Targets clean energy, sustainable agriculture, climate adaptation, and green technology.",
        "category": "grant",
        "tags": ["India", "climate", "cleantech", "sustainability", "green", "energy"],
        "eligibility_summary": "India-based startup with a climate or sustainability focus. Early to growth stage.",
        "startup_stages": ["idea", "validation", "mvp", "pre-seed"],
        "geography": ["India"],
        "domain_focus": ["climate", "cleantech", "sustainability"],
        "founder_criteria": [],
        "funding_amount": "Varies by cohort",
        "benefits": ["Grant funding", "Network access", "Visibility", "Mentorship"],
        "required_docs": ["Application form", "Climate impact description", "Team profile"],
        "official_link": "https://indiaclimate.org/",
        "deadline": "Rolling",
        "source_name": "India Climate Collaborative",
    },
    {
        "id": "student-startup-policy-karnataka",
        "title": "Karnataka Startup Policy — Student Startup Program",
        "organization": "Karnataka Innovation and Technology Society (KITS)",
        "description": "State government program supporting student entrepreneurs in Karnataka with grants, incubation, and mentorship. Part of Karnataka's Startup Policy 2022-27.",
        "category": "student",
        "tags": ["India", "Karnataka", "student", "state-government", "grant"],
        "eligibility_summary": "Student or recent graduate from a Karnataka institution. Early-stage startup or idea stage.",
        "startup_stages": ["idea", "validation"],
        "geography": ["India", "Karnataka"],
        "domain_focus": [],
        "founder_criteria": ["student"],
        "funding_amount": "Up to ₹5 Lakhs",
        "benefits": ["Seed grant", "Incubation support", "Government recognition", "Mentorship"],
        "required_docs": ["Student ID", "Innovation proposal", "Faculty recommendation"],
        "official_link": "https://startup.karnataka.gov.in/",
        "deadline": "Rolling",
        "source_name": "Karnataka Startup Mission",
    },
    {
        "id": "tlabs-india-accelerator",
        "title": "T-Labs Accelerator",
        "organization": "T-Labs (Tata Communications)",
        "description": "Deep-tech accelerator by Tata Communications for startups working on enterprise technology, networking, cloud, and digital infrastructure.",
        "category": "accelerator",
        "tags": ["India", "deeptech", "enterprise", "B2B", "SaaS", "networking"],
        "eligibility_summary": "Tech startup with enterprise or B2B focus. MVP to pre-seed stage preferred.",
        "startup_stages": ["mvp", "pre-seed", "seed"],
        "geography": ["India", "Global"],
        "domain_focus": ["SaaS", "AI", "deeptech", "enterprise"],
        "founder_criteria": [],
        "funding_amount": "Program support + investor connects",
        "benefits": ["Tata network", "Enterprise customers", "Mentorship", "Product validation"],
        "required_docs": ["Application form", "Pitch deck", "Product demo"],
        "official_link": "https://www.tatacommunications.com/t-labs/",
        "deadline": "Cohort-based",
        "source_name": "Tata Communications",
    },
    {
        "id": "wamtech-women-founder-program",
        "title": "WEP — Women Entrepreneurship Platform",
        "organization": "NITI Aayog",
        "description": "Government platform for women entrepreneurs in India. Provides mentorship, credit linkages, market access, and incubation support.",
        "category": "fellowship",
        "tags": ["India", "women", "government", "all-sectors", "mentorship"],
        "eligibility_summary": "Women-led startup or entrepreneur in India. Any stage.",
        "startup_stages": ["idea", "validation", "mvp", "pre-seed"],
        "geography": ["India"],
        "domain_focus": [],
        "founder_criteria": ["women"],
        "funding_amount": "Non-monetary (access & mentorship)",
        "benefits": ["Mentorship", "Credit linkages", "Market access", "Government recognition"],
        "required_docs": ["Application form", "Business overview"],
        "official_link": "https://wep.gov.in/",
        "deadline": "Rolling",
        "source_name": "NITI Aayog WEP",
    },
    {
        "id": "iit-bombay-sine-incubator",
        "title": "SINE Incubator — IIT Bombay",
        "organization": "Society for Innovation and Entrepreneurship, IIT Bombay",
        "description": "One of India's top university incubators. Supports deep-tech, engineering, and science-based startups. Strong alumni network and investor connections.",
        "category": "incubator",
        "tags": ["India", "deeptech", "engineering", "science", "university", "IIT"],
        "eligibility_summary": "Technology startup preferably with IIT Bombay connection (alumni, students, faculty). Open to external startups too.",
        "startup_stages": ["idea", "validation", "mvp", "pre-seed"],
        "geography": ["India"],
        "domain_focus": ["deeptech", "AI", "hardware", "biotech", "engineering"],
        "founder_criteria": ["university"],
        "funding_amount": "Up to ₹25 Lakhs + facilities",
        "benefits": ["Seed funding", "Lab access", "IIT Bombay network", "IP support", "Mentorship"],
        "required_docs": ["Application form", "Innovation description", "Team details"],
        "official_link": "https://www.sineiitb.org/",
        "deadline": "Cohort-based",
        "source_name": "SINE IIT Bombay",
    },
    {
        "id": "global-hackathon-devpost",
        "title": "Devpost Global Hackathons (AI & Tech)",
        "organization": "Devpost",
        "description": "Platform hosting hundreds of global online hackathons with prizes ranging from $5K to $1M+. Great for founders to validate ideas, win prizes, and build MVPs.",
        "category": "hackathon",
        "tags": ["Global", "hackathon", "AI", "tech", "prizes", "online", "validation"],
        "eligibility_summary": "Open to any developer or founder globally. Most hackathons allow solo or team entries.",
        "startup_stages": ["idea", "validation", "mvp"],
        "geography": ["Global"],
        "domain_focus": [],
        "founder_criteria": ["student", "first-time-founder"],
        "funding_amount": "Prizes vary ($1K–$1M+)",
        "benefits": ["Cash prizes", "Validation signal", "Visibility", "Network", "MVP forcing function"],
        "required_docs": ["Project submission", "Demo video"],
        "official_link": "https://devpost.com/hackathons",
        "deadline": "Rolling (multiple hackathons)",
        "source_name": "Devpost",
    },
    {
        "id": "techstars-global",
        "title": "Techstars Accelerator",
        "organization": "Techstars",
        "description": "Global startup accelerator with programs in 50+ cities. $120K investment for 6% equity. Strong mentor network and alumni community.",
        "category": "accelerator",
        "tags": ["Global", "accelerator", "seed", "pre-seed", "mentor-driven"],
        "eligibility_summary": "Startup at MVP or early traction stage. Any domain. Global applications open.",
        "startup_stages": ["mvp", "pre-seed", "seed"],
        "geography": ["Global"],
        "domain_focus": [],
        "founder_criteria": [],
        "funding_amount": "$120K for 6% equity",
        "benefits": ["$120K investment", "3-month program", "Mentor network", "Demo Day", "Alumni community"],
        "required_docs": ["Application form", "Pitch video", "Team info"],
        "official_link": "https://www.techstars.com/apply",
        "deadline": "Cohort-based (check portal)",
        "source_name": "Techstars",
    },
]
